name: Sync to public repo

on:
  push:
    branches:
      - main
jobs:
  sync-oracle-node-to-public-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup public monorepo access
        uses: redstone-finance/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.PUBLIC_REPO_KEY }}
      - name: Sync to public monorepo
        run: |

          # Configure user
          git config --global user.name "Syncer Man"
          git config --global user.email "syncer@redstone.finance"

          # Remove from all commits
          BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})

          curl https://raw.githubusercontent.com/newren/git-filter-repo/cbc6535/git-filter-repo --output git-filter-repo
          python3 git-filter-repo --refs "$BRANCH_NAME" --force --paths-from-file .paths-to-include-in-public-repo

          # Add as remote
          git remote add target git@github.com:redstone-finance/redstone-oracles-monorepo-future-public.git

          # Push modified
          git push -f target "$BRANCH_NAME"
